<script setup lang="ts">
import { ArrowRight, CheckCircle2, CircleAlert, LoaderCircle, RotateCcw, Wrench } from 'lucide-vue-next'
import type { ProductGymBuildView } from '@/types/product'

defineProps<{ build: ProductGymBuildView | null; loading: boolean; starting: boolean; error: string | null }>()
const emit = defineEmits<{ retry: []; start: [] }>()
</script>

<template>
  <section v-if="build" class="gym-build-panel" aria-live="polite">
    <div class="build-status" :class="build.job.status"><CheckCircle2 v-if="build.job.status === 'ready'" :size="17" aria-hidden="true" /><CircleAlert v-else-if="build.job.status === 'failed'" :size="17" aria-hidden="true" /><LoaderCircle v-else :size="17" class="spin" aria-hidden="true" /><div><span class="eyebrow">Gym builder · {{ build.job.status }}</span><h2>{{ build.job.status === 'ready' ? (build.runtime.status === 'active' ? '实践环境已经激活' : '实践案例已经准备好') : build.job.status === 'failed' ? '环境构建没有完成' : '正在构建一次可执行实践' }}</h2><p v-if="build.job.status === 'failed'">{{ build.job.failureMessage || '构建服务返回了失败状态，请重试。' }}</p><p v-else-if="build.job.status === 'ready' && build.runtime.status === 'expired'">之前的实验运行已失效，可以重新启动 Gym；实践记录会继续保留。</p><p v-else-if="build.job.status === 'ready' && build.runtime.status === 'active'">当前实验运行仍然有效，可以直接回到实践页面继续学习。</p><p v-else-if="build.job.status === 'ready'">案例内容已经通过服务端校验，可以启动对应实验环境。</p><p v-else>Agent 正在根据当前节点目标选择案例内容，完成后会自动恢复此页面状态。</p></div></div>
    <dl class="build-facts"><div><dt>环境</dt><dd>{{ build.environment.displayName }}</dd></div><div><dt>能力</dt><dd>{{ build.environment.capabilityKey }}</dd></div><div><dt>构建尝试</dt><dd>{{ build.job.attemptCount || 0 }}</dd></div></dl>
    <div class="build-actions"><button v-if="build.job.status === 'failed'" type="button" class="secondary-button" :disabled="loading" @click="emit('retry')"><RotateCcw :size="14" aria-hidden="true" />重试构建</button><button v-if="build.job.status === 'ready'" type="button" class="primary-button" :disabled="starting" @click="emit('start')"><Wrench :size="14" aria-hidden="true" />{{ starting ? '正在启动…' : build.runtime.status === 'active' ? '继续进入知行 Gym' : build.runtime.status === 'expired' ? '重新启动 Gym' : '进入知行 Gym' }}<ArrowRight :size="14" aria-hidden="true" /></button></div>
    <p v-if="error" class="build-error" role="alert">{{ error }}</p>
  </section>
</template>

<style scoped>
.gym-build-panel { display: grid; gap: 18px; margin-top: 24px; padding: 20px; border-top: 2px solid var(--orange); background: var(--paper-deep); }.build-status { display: flex; align-items: flex-start; gap: 12px; color: var(--orange); }.build-status.ready { color: var(--green); }.build-status.failed { color: var(--red); }.build-status h2 { margin: 7px 0 0; color: var(--ink); font: 400 24px/1.25 var(--serif); }.build-status p { max-width: 660px; margin: 8px 0 0; color: var(--muted); font-size: 11px; line-height: 1.6; }.build-facts { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 16px; margin: 0; padding-top: 13px; border-top: 1px solid var(--line); }.build-facts div { display: grid; gap: 5px; }.build-facts dt { color: #7e8881; font: 9px var(--mono); }.build-facts dd { margin: 0; color: var(--ink); font-size: 11px; overflow-wrap: anywhere; }.build-actions { display: flex; gap: 9px; }.build-actions button { display: inline-flex; align-items: center; gap: 6px; min-height: 35px; padding: 8px 11px; border: 1px solid var(--blue); background: var(--blue); color: #fff; font-size: 10px; cursor: pointer; }.build-actions .primary-button { border-color: #995436; background: #995436; color: var(--white); }.build-actions .primary-button:hover { border-color: #82462c; background: #82462c; }.build-actions .secondary-button { border-color: var(--line); background: var(--paper); color: var(--blue); }.build-actions .secondary-button:hover { border-color: var(--orange); color: #995436; background: var(--orange-soft); }.build-error { margin: 0; padding: 9px 11px; border-left: 2px solid var(--red); background: var(--red-soft); color: var(--red); font-size: 10px; line-height: 1.5; }.spin { animation: spin 1s linear infinite; }@keyframes spin { to { transform: rotate(360deg); } }@media (max-width: 620px) { .build-facts { grid-template-columns: 1fr; gap: 11px; }.build-actions { flex-direction: column; }.build-actions button { width: 100%; justify-content: center; } }
</style>
