<script setup lang="ts">
import { ArrowRight, CheckCircle2, History, RefreshCw, Sparkles } from 'lucide-vue-next'
import { computed, watch } from 'vue'
import WritingEvidenceInspector from './WritingEvidenceInspector.vue'
import type { ProductWritingCluster, ProductWritingClusterDetail, ProductWritingClusterOverview } from '@/types/product'

const props = defineProps<{ overview: ProductWritingClusterOverview; detail: ProductWritingClusterDetail | null; activeClusterId: string | null; filter: string; loading: boolean; detailLoading: boolean; saving: boolean }>()
const emit = defineEmits<{ open: [clusterId: string]; status: [cluster: ProductWritingCluster, status: ProductWritingCluster['status']]; filter: [value: string]; refresh: []; replay: []; continue: []; 'load-more': [] }>()
const selectedCluster = computed(() => props.overview.clusters.find((cluster) => cluster.id === props.activeClusterId) ?? props.overview.clusters[0] ?? null)

watch(() => props.overview.clusters, (clusters) => {
  if (!props.activeClusterId && clusters[0]) emit('open', clusters[0].id)
}, { immediate: true })
</script>

<template>
  <section class="curation-shell" aria-labelledby="curation-title">
    <header class="curation-header"><div><span class="eyebrow">01 · Evidence map</span><h2 id="curation-title">确认一条完整的证据链。</h2><p>左侧选择一个聚类，右侧确认它是否值得写并检查对应的原始记录。原始记录保持不变。</p></div><div class="curation-header-actions"><button class="secondary-button replay-button" type="button" title="从实践事件中补齐缺失记录" :disabled="loading" @click="emit('replay')"><History :size="13" aria-hidden="true" />重放记录</button><button class="icon-button" type="button" title="重新整理证据地图" aria-label="重新整理证据地图" :disabled="loading" @click="emit('refresh')"><RefreshCw :size="14" aria-hidden="true" /></button></div></header>
    <div class="curation-progress"><div><strong>{{ overview.acceptedCount }} / {{ overview.totalCount }}</strong><span>个聚类已确认</span></div><div class="progress-track" aria-hidden="true"><span :style="{ width: `${overview.totalCount ? (overview.acceptedCount / overview.totalCount) * 100 : 0}%` }" /></div><span class="progress-note">{{ overview.canGenerateOutline ? '核心证据已齐，可以生成大纲。' : '至少确认问题、证据和验证三个聚类。' }}</span><button v-if="overview.canGenerateOutline" class="primary-button" type="button" @click="emit('continue')">进入大纲 <ArrowRight :size="13" aria-hidden="true" /></button></div>
    <div v-if="overview.curation.status === 'queued' || overview.curation.status === 'running'" class="curation-notice"><Sparkles :size="13" aria-hidden="true" />模型正在润色卡片摘要，当前规则摘要已经可以确认。</div>
    <div v-else-if="overview.curation.status === 'failed'" class="curation-notice muted"><Sparkles :size="13" aria-hidden="true" />模型摘要暂不可用，当前内容来自可追溯的实验记录。</div>
    <div class="curation-body">
      <nav class="cluster-nav" aria-label="证据聚类"><div class="nav-heading"><span>证据聚类</span><small>{{ overview.totalCount }} 个判断簇</small></div><button v-for="cluster in overview.clusters" :key="cluster.id" type="button" :class="{ active: selectedCluster?.id === cluster.id, accepted: cluster.status === 'accepted', rejected: cluster.status === 'rejected' }" @click="emit('open', cluster.id)"><span class="nav-marker"><CheckCircle2 v-if="cluster.status === 'accepted'" :size="13" aria-hidden="true" /><span v-else>{{ String(cluster.position).padStart(2, '0') }}</span></span><span><strong>{{ cluster.title }}</strong><small>{{ cluster.status === 'accepted' ? '已纳入' : cluster.status === 'rejected' ? '暂不纳入' : '待确认' }} · {{ cluster.memberCount }} 条</small></span></button></nav>
      <WritingEvidenceInspector :cluster="selectedCluster" :detail="detail" :loading="detailLoading" :filter="filter" :saving="saving" @accept="selectedCluster && emit('status', selectedCluster, 'accepted')" @reject="selectedCluster && emit('status', selectedCluster, 'rejected')" @reset="selectedCluster && emit('status', selectedCluster, 'pending')" @update:filter="emit('filter', $event)" @load-more="emit('load-more')" />
    </div>
  </section>
</template>

<style scoped>
.curation-shell { display: grid; min-width: 0; border-top: 2px solid var(--blue); background: var(--paper-muted); }
.curation-header { display: flex; justify-content: space-between; gap: 16px; padding: 18px 20px 15px; border-bottom: 1px solid var(--line); }.curation-header h2 { margin: 6px 0 0; color: var(--ink); font: 400 24px/1.2 var(--serif); }.curation-header p { max-width: 700px; margin: 7px 0 0; color: var(--muted); font-size: 11px; line-height: 1.55; }.curation-header-actions { display: flex; align-items: start; gap: 8px; }.replay-button { display: inline-flex; align-items: center; gap: 6px; white-space: nowrap; }
.icon-button { display: grid; place-items: center; align-self: start; width: 28px; height: 28px; border: 1px solid #b8c1ec; background: transparent; color: var(--blue); cursor: pointer; }
.curation-progress { display: flex; align-items: center; gap: 14px; min-width: 0; padding: 11px 20px; border-bottom: 1px solid var(--line); background: #fff; }.curation-progress div:first-child { display: grid; gap: 3px; flex: 0 0 auto; }.curation-progress strong { color: var(--ink); font: 18px var(--serif); }.curation-progress span { color: var(--muted); font: 9px var(--mono); }.progress-track { flex: 0 1 170px; height: 4px; background: var(--line-soft); }.progress-track span { display: block; height: 100%; background: var(--green); transition: width .2s ease; }.progress-note { min-width: 0; }.curation-progress .primary-button { display: inline-flex; align-items: center; gap: 6px; margin-left: auto; white-space: nowrap; }
.curation-notice { display: flex; align-items: center; gap: 7px; padding: 9px 20px; border-bottom: 1px solid var(--line); color: var(--blue); font-size: 10px; }.curation-notice.muted { color: var(--muted); }
.curation-body { display: grid; grid-template-columns: 245px minmax(0, 1fr); height: min(680px, calc(100vh - 310px)); min-height: 520px; overflow: hidden; }.cluster-nav { display: grid; align-content: start; gap: 1px; overflow-y: auto; padding: 10px 0; border-right: 1px solid var(--line); background: var(--paper-muted); }.nav-heading { display: flex; justify-content: space-between; gap: 8px; padding: 5px 14px 10px; color: var(--ink); font-size: 10px; }.nav-heading small { color: var(--muted); font: 8px var(--mono); }.cluster-nav button { display: grid; grid-template-columns: 25px minmax(0, 1fr); gap: 8px; align-items: center; padding: 11px 14px; border: 0; border-left: 2px solid transparent; background: transparent; color: var(--muted); text-align: left; cursor: pointer; }.cluster-nav button:hover, .cluster-nav button.active { border-left-color: var(--blue); background: #fff; color: var(--blue); }.cluster-nav button.accepted { color: var(--green); }.cluster-nav button.rejected { opacity: .65; }.nav-marker { display: grid; place-items: center; width: 23px; height: 23px; border: 1px solid currentColor; font: 9px var(--mono); }.cluster-nav strong, .cluster-nav small { display: block; }.cluster-nav strong { overflow: hidden; font-size: 11px; font-weight: 600; text-overflow: ellipsis; white-space: nowrap; }.cluster-nav small { margin-top: 3px; color: var(--muted); font: 8px var(--mono); }.evidence-inspector { min-height: 0; overflow: hidden; }
@media (max-width: 1020px) { .curation-body { grid-template-columns: 190px minmax(0, 1fr); height: auto; min-height: 0; overflow: visible; }.curation-body > .evidence-inspector { min-height: 560px; border-top: 0; border-left: 0; } }
@media (max-width: 760px) { .curation-progress { align-items: start; flex-wrap: wrap; }.progress-track { order: 3; flex-basis: 100%; }.progress-note { flex-basis: 100%; }.curation-body { display: block; }.cluster-nav { display: flex; overflow-x: auto; border-right: 0; border-bottom: 1px solid var(--line); }.nav-heading { display: none; }.cluster-nav button { flex: 0 0 154px; border-left: 0; border-bottom: 2px solid transparent; }.cluster-nav button:hover, .cluster-nav button.active { border-bottom-color: var(--blue); }.cluster-detail { min-height: 340px; }.curation-body > .evidence-inspector { height: 430px; max-height: 430px; } }
</style>
