-- Deploy manually with a platform-provisioned MySQL 8 admin connection.
-- The application must not run this file during startup.

CREATE DATABASE IF NOT EXISTS `zhixing_lab_slow` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS `zhixing_lab_deadlock` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS `zhixing_lab_pagination` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `zhixing_lab_slow`.`lab_fixture_meta` (
  `id` TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  `fixture_version` VARCHAR(64) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `zhixing_lab_slow`.`lab_seed_numbers` (
  `n` INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS `zhixing_lab_slow`.`orders` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `user_id` BIGINT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `total_amount` DECIMAL(12, 2) NOT NULL,
  KEY `idx_orders_user_id` (`user_id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `zhixing_lab_deadlock`.`lab_fixture_meta` (
  `id` TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  `fixture_version` VARCHAR(64) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `zhixing_lab_deadlock`.`accounts` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `account_name` VARCHAR(64) NOT NULL,
  `balance` DECIMAL(12, 2) NOT NULL,
  `version` INT NOT NULL
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `zhixing_lab_pagination`.`lab_fixture_meta` (
  `id` TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  `fixture_version` VARCHAR(64) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `zhixing_lab_pagination`.`lab_seed_numbers` (
  `n` INT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS `zhixing_lab_pagination`.`events` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `created_at` DATETIME NOT NULL,
  `event_type` VARCHAR(32) NOT NULL,
  `payload` VARCHAR(255) NOT NULL,
  KEY `idx_events_created_id` (`created_at`, `id`)
) ENGINE = InnoDB;

INSERT INTO `zhixing_lab_slow`.`lab_fixture_meta` (`id`, `fixture_version`)
VALUES (1, '2026-08-28.1')
ON DUPLICATE KEY UPDATE `fixture_version` = VALUES(`fixture_version`);

INSERT INTO `zhixing_lab_pagination`.`lab_fixture_meta` (`id`, `fixture_version`)
VALUES (1, '2026-08-28.1')
ON DUPLICATE KEY UPDATE `fixture_version` = VALUES(`fixture_version`);

INSERT INTO `zhixing_lab_deadlock`.`lab_fixture_meta` (`id`, `fixture_version`)
VALUES (1, '2026-08-28.1')
ON DUPLICATE KEY UPDATE `fixture_version` = VALUES(`fixture_version`);

INSERT IGNORE INTO `zhixing_lab_slow`.`lab_seed_numbers` (`n`)
SELECT ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000 + ten_thousands.n * 10000
FROM
  (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
  CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
  CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds
  CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) thousands
  CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ten_thousands
;

INSERT IGNORE INTO `zhixing_lab_pagination`.`lab_seed_numbers` (`n`)
SELECT ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000 + ten_thousands.n * 10000
FROM
  (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
  CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
  CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds
  CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) thousands
  CROSS JOIN (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ten_thousands
;
