import type { LabCaseId, LabExecutionResult, LabSessionName } from './lab'

export type CaseStage = 'observe' | 'hypothesize' | 'inspect' | 'attempt' | 'verify' | 'resolved'

export interface ProductIntake { id: string; learnerId: string; goal: string; technology: string; outcome: string | null; weeklyMinutes: number | null; status: string; createdAt: string; updatedAt: string }
export interface ProductPlanUnit { id: string; planId: string; position: number; title: string; objective: string; caseId: LabCaseId | null; status: 'upcoming' | 'current' | 'completed'; sourceRefs: string[] }
export interface ProductPlan { id: string; learnerId: string; intakeId: string; title: string; goal: string; sourceStatus: string; status: string; createdAt: string; updatedAt: string; units: ProductPlanUnit[] }
export interface ProductPracticeRun { id: string; learnerId: string; planUnitId: string | null; caseId: LabCaseId; labRunId: string | null; stage: CaseStage; hintLevel: number; noProgressCount: number; status: 'active' | 'ready_to_close' | 'resolved' | 'ended'; createdAt: string; updatedAt: string }
export interface ProductArtifact { id: string; learnerId: string; practiceRunId: string | null; kind: string; sourceKind: string; verificationStatus: string; content: string; metadata: Record<string, unknown>; checksum: string; createdAt: string }
export interface ProductEvent { id: string; sequence: number; actor: string; type: string; stage: CaseStage; payload: Record<string, unknown>; artifactRefs: string[]; createdAt: string }
export interface ProductPathNode { id: string; stage: CaseStage; title: string; judgment: string; outcome: string; judgmentChange: string | null; nextGap: string | null; importance: string; eventRefs: string[]; artifactRefs: string[]; createdAt: string }
export interface ProductStageMemory { id: string; stage: CaseStage; memory: Record<string, unknown>; sourceEventRefs: string[]; version: number; updatedAt: string }
export interface ProductMemory { id: string; learnerId: string; category: string; topic: string; status: string; statement: string; scope: string; confidence: number; evidenceRefs: string[]; userNote: string | null; updatedAt: string }
export interface ProductTutorResponse { response: string; intent: string; currentGap: string; nextQuestion: string; suggestedActions: string[]; evidenceRefs: string[]; sourceRefs: Array<{ sourceId: string; reason: string }>; provider: 'model' | 'scripted'; sourceStatus: string }
export interface ProductTutorMessage { id: string; role: 'user' | 'assistant'; content: string; source?: string }
export interface ProductTutorSource { id: string; title: string; author: string | null; url: string; excerpt: string; retrievedAt: string; provider: string; role: string; reason: string }
export interface ProductPracticePin { id: string; learnerId: string; practiceRunId: string; targetType: 'artifact' | 'source'; targetId: string; title: string; body: string; source: string; url: string | null; createdAt: string }
export interface ProductPracticeHistoryItem { id: string; caseId: LabCaseId; stage: CaseStage; status: 'active' | 'ready_to_close' | 'resolved' | 'ended'; createdAt: string; updatedAt: string; lastActivityAt: string; lastTutorProvider: string | null; lastTutorSourceStatus: string | null; labState: 'active' | 'reopen_required' | 'none' }
export interface ProductPracticeHistoryPage { items: ProductPracticeHistoryItem[]; nextCursor: string | null }
export type ProductTutorStreamEvent =
  | { type: 'accepted'; invocationId: string }
  | { type: 'retrieval_started'; invocationId: string }
  | { type: 'sources'; invocationId: string; status: string; items: ProductTutorSource[]; errorCode?: string }
  | { type: 'answer_delta'; invocationId: string; delta: string }
  | { type: 'completed'; invocationId: string; run: ProductPracticeRun; tutor: ProductTutorResponse; snapshot: ProductSnapshot; sources: ProductTutorSource[] }
  | { type: 'failed'; invocationId: string; code: string; message: string; retryable: boolean }
export interface ProductPracticeCompletionCheck { key: string; label: string; complete: boolean; detail: string }
export interface ProductPracticeCompletion { status: 'in_progress' | 'ready_to_close' | 'resolved' | 'ended'; ready: boolean; checks: ProductPracticeCompletionCheck[]; missing: string[]; summary: string }
export interface ProductSnapshot { run: ProductPracticeRun; events: ProductEvent[]; artifacts: ProductArtifact[]; pathNodes: ProductPathNode[]; stageMemories: ProductStageMemory[]; memories: ProductMemory[]; tutorTurns: Array<{ id: string; userArtifactId: string | null; assistantArtifactId: string | null; mode: string; provider: string; sourceStatus: string; createdAt: string }>; pins: ProductPracticePin[]; completion: ProductPracticeCompletion }
export interface ProductLabRun { runId: string; caseId: LabCaseId; revision: number; status: 'active'; fixtureVersion: string; expiresAt: string; idleExpiresAt: string; sessions: Array<{ id: string; name: LabSessionName; status: 'open' | 'closed' }> }
export interface ProductPracticeStart { practice: ProductPracticeRun; lab?: { run: ProductLabRun; accessToken: string }; queue?: { ticketId: string; caseId: LabCaseId; status: string; position?: number; pollAfterMs?: number; expiresAt: string } }
export interface ProductLabAccess { status: 'waiting' | 'ready' | 'expired' | 'cancelled'; ticketId?: string; run?: ProductLabRun; accessToken?: string }
export interface ProductLabExecution { execution: LabExecutionResult; run: ProductPracticeRun; snapshot: ProductSnapshot }
export type ProductWritingStatus = 'materials_ready' | 'outline_review' | 'article_review' | 'ready_for_preview'
export type ProductWritingDocumentKind = 'outline' | 'article'
export interface ProductWritingMaterial { id: string; projectId: string; category: string; refType: 'artifact' | 'source' | 'event'; refId: string; title: string; excerpt: string; selected: boolean; verificationStatus: string; metadata: Record<string, unknown>; createdAt: string }
export interface ProductWritingBlock { id: string; documentId: string; sectionId: string | null; position: number; content: string; blockType: 'heading' | 'paragraph' | 'code' | 'quote' | 'list'; evidenceRefs: string[]; sourceRefs: string[]; referenceRoles: Record<string, 'lab' | 'source' | 'inherited'>; referenceMarkers: string[]; revision: number; createdAt: string; updatedAt: string }
export interface ProductWritingSection { id: string; documentId: string; sectionKey: string; position: number; title: string; content: string; required: boolean; status: 'empty' | 'generated' | 'confirmed'; evidenceRefs: string[]; sourceRefs: string[]; updatedAt: string; blocks: ProductWritingBlock[] }
export interface ProductWritingClaim { id: string; documentId: string; sectionId: string; text: string; kind: string; status: 'supported' | 'needs_review' | 'unsupported'; evidenceRefs: string[]; sourceRefs: string[]; createdAt: string }
export interface ProductWritingReviewItem { id: string; projectId: string; code: string; severity: 'info' | 'warning' | 'blocking'; status: 'open' | 'resolved' | 'dismissed'; message: string; sectionId: string | null; createdAt: string }
export interface ProductWritingDocument { id: string; projectId: string; kind: ProductWritingDocumentKind; revision: number; status: string; title: string; summary: string; evidencePackId: string | null; format: 'sectioned' | 'narrative'; contentMarkdown: string; sections: ProductWritingSection[]; claims: ProductWritingClaim[]; blocks: ProductWritingBlock[]; createdAt: string; updatedAt: string }
export interface ProductWritingProject { id: string; learnerId: string; practiceRunId: string; articleType: 'engineering_practice_review'; status: ProductWritingStatus; evidenceSnapshot: { capturedAt: string | null; materialIds: string[] }; materials: ProductWritingMaterial[]; documents: ProductWritingDocument[]; reviewItems: ProductWritingReviewItem[]; createdAt: string; updatedAt: string }
export type ProductWritingClusterKey = 'problem' | 'hypothesis' | 'evidence' | 'attempts' | 'solution' | 'principles'
export type ProductWritingClusterStatus = 'pending' | 'accepted' | 'rejected'
export interface ProductWritingCluster { id: string; projectId: string; clusterKey: ProductWritingClusterKey; position: number; title: string; ruleSummary: string; modelSummary: string | null; relevance: string; userNote: string | null; status: ProductWritingClusterStatus; summaryStatus: 'rule_ready' | 'queued' | 'running' | 'model_ready' | 'model_failed'; revision: number; sourceFingerprint: string; memberCount: number; duplicateCount: number; createdAt: string; updatedAt: string }
export interface ProductWritingCapsule { id: string; projectId: string; clusterId: string; inputFingerprint: string; version: number; ruleSummary: string; modelSummary: string | null; keyFindings: string[]; turningPoints: string[]; unresolvedQuestions: string[]; status: 'rule_ready' | 'queued' | 'running' | 'model_ready' | 'model_failed'; rawCount: number; representativeCount: number; omittedCount: number; modelFailureCode: string | null; modelFailureMessage: string | null; createdAt: string; updatedAt: string }
export interface ProductWritingCapsuleMember { id: string; capsuleId: string; refType: 'artifact' | 'source' | 'path_node'; refId: string; role: 'primary' | 'supporting' | 'duplicate' | 'context'; displayOrder: number; title: string; excerpt: string; kind: string; verificationStatus: string }
export interface ProductWritingEvidencePack { id: string; projectId: string; inputFingerprint: string; version: number; snapshot: Record<string, unknown>; nodeCount: number; charCount: number; status: 'active' | 'superseded'; createdAt: string }
export interface ProductWritingGenerationJob { id: string; projectId: string; kind: 'capsule' | 'outline' | 'article'; inputFingerprint: string; clientRequestId: string | null; evidencePackId: string | null; outlineDocumentId: string | null; status: 'queued' | 'running' | 'succeeded' | 'failed' | 'interrupted'; attemptCount: number; provider: string | null; model: string | null; failureCode: string | null; failureMessage: string | null; resultDocumentId: string | null; createdAt: string; updatedAt: string; completedAt: string | null }
export type ProductWritingDraftPhase = 'indexing' | 'outlining' | 'drafting' | 'humanizing' | 'checking' | 'ready' | 'failed'
export interface ProductWritingDraftRun { id: string; projectId: string; inputFingerprint: string; status: 'queued' | 'running' | 'succeeded' | 'failed' | 'interrupted'; phase: ProductWritingDraftPhase; evidencePackId: string | null; outlineJobId: string | null; articleJobId: string | null; draftJobId: string | null; humanizeJobId: string | null; outlineDocumentId: string | null; articleDocumentId: string | null; attemptCount: number; failureCode: string | null; failureMessage: string | null; createdAt: string; updatedAt: string; completedAt: string | null }
export interface ProductWritingEvidenceReference { refType: 'artifact' | 'event' | 'source' | 'path_node'; refId: string; title: string; content: string; kind: string; verificationStatus: string; role: 'lab' | 'source' | 'inherited'; url: string | null; author: string | null }
export interface ProductWritingBlockEvidence { block: ProductWritingBlock; references: ProductWritingEvidenceReference[] }
export interface ProductWritingWorkspace { practiceRunId: string; draftRun: ProductWritingDraftRun | null; project: ProductWritingProject | null }
export interface ProductWritingClusterOverview { projectId: string; practiceRunId: string; clusters: ProductWritingCluster[]; capsules: ProductWritingCapsule[]; acceptedCount: number; totalCount: number; requiredAccepted: string[]; canGenerateOutline: boolean; curation: { status: 'not_started' | 'queued' | 'running' | 'succeeded' | 'failed'; jobId: string | null; error: string | null } }
export interface ProductWritingClusterMember { id: string; clusterId: string; refType: 'artifact' | 'source' | 'path_node'; refId: string; role: 'primary' | 'supporting' | 'duplicate' | 'context'; displayOrder: number; title: string; excerpt: string; kind: string; verificationStatus: string; createdAt: string }
export interface ProductWritingClusterDetail { cluster: ProductWritingCluster; members: ProductWritingClusterMember[]; nextCursor: string | null }
