import { randomUUID } from 'node:crypto'
import type { ProductRepository } from './product-repository.js'
import type { EnvironmentBuildOrchestrator } from './gym-build-service.js'

type Row = Record<string, unknown>
const now = () => new Date().toISOString()
const parse = <T>(raw: unknown, fallback: T): T => { try { return typeof raw === 'string' ? JSON.parse(raw) as T : fallback } catch { return fallback } }
const cardPublic = (row: Row) => ({ id: String(row.id), planUnitId: String(row.plan_unit_id), status: String(row.status), version: Number(row.version), ...parse<Record<string, unknown>>(row.public_json, {}), sourceQuality: Number(row.source_quality), createdAt: String(row.created_at), readyAt: row.ready_at ? String(row.ready_at) : null })

export class MixedGymService {
  constructor(private readonly repository: ProductRepository, private readonly build: EnvironmentBuildOrchestrator) {}
  private unit(learnerId: string, unitId: string) { const row = this.repository.db.prepare('SELECT u.*, p.id AS plan_id FROM plan_units u JOIN learning_plans p ON p.id=u.plan_id WHERE u.id=? AND p.learner_id=?').get(unitId, learnerId) as Row | undefined; if (!row) throw new Error('学习单元不存在'); return row }
  private event(cardId: string, learnerId: string, type: string, payload: Record<string, unknown>, key?: string) { const sequence = Number((this.repository.db.prepare('SELECT COALESCE(MAX(sequence),0)+1 AS n FROM practice_card_events WHERE practice_card_id=?').get(cardId) as Row).n); this.repository.db.prepare('INSERT INTO practice_card_events(id, practice_card_id, learner_id, sequence, type, payload_json, client_request_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run(randomUUID(), cardId, learnerId, sequence, type, JSON.stringify(payload), key ?? null, now()) }
  createCard(learnerId: string, unitId: string, input: { intent?: Record<string, unknown>; sourceIds?: string[]; clientRequestId: string }) { const unit = this.unit(learnerId, unitId); const existing = this.repository.db.prepare('SELECT * FROM practice_cards WHERE learner_id=? AND plan_unit_id=? AND client_request_id=?').get(learnerId, unitId, input.clientRequestId) as Row | undefined; if (existing) return cardPublic(existing); const derivedIntent = { targetCapability: String(unit.title), objective: String(unit.objective), learningMode: String(unit.learning_mode), planUnitId: unitId }; const sources = this.repository.db.prepare("SELECT * FROM learner_source_items WHERE learner_id=? ORDER BY updated_at DESC LIMIT 12").all(learnerId) as Row[]; const selected = sources.filter(source => `${String(source.title)} ${String(source.excerpt)}`.toLowerCase().includes(String(unit.title).toLowerCase().slice(0, 12))).slice(0, 2); const usableSources = selected.length ? selected : []; const quality = usableSources.length ? Math.min(1, usableSources.reduce((n, source) => n + (String(source.excerpt).length > 120 ? 0.7 : 0.45), 0) / usableSources.length) : 0; const activities = [
    { key: 'concept', type: 'concept', prompt: `解释 ${String(unit.title)} 的核心概念。` },
    { key: 'knowledge-1', type: 'knowledge_check', prompt: '选择最符合该概念的说法。', choices: ['正确做法', '常见误解'] },
    { key: 'knowledge-2', type: 'knowledge_check', prompt: '用自己的话说明边界条件。' },
    { key: 'scenario', type: 'scenario_reasoning', prompt: `在 ${String(unit.title)} 的情境中做判断并说明理由。` },
    ...(String(unit.learning_mode) === 'lab' || String(unit.learning_mode) === 'workspace' ? [{ key: 'runtime', type: 'runtime_practice', prompt: '在受控运行环境中完成并验证操作。' }] : []),
    { key: 'reflection', type: 'reflection', prompt: '记录你还不确定的一点，以及下一步验证方法。' },
  ]; const publicJson = { title: String(unit.title), summary: quality >= .65 ? String(unit.objective) : `${String(unit.objective)}（基于通用知识生成，尚无足够来源）`, mode: activities.some(a => a.type === 'runtime_practice') ? 'mixed' : 'knowledge_only', completionPolicy: { requiresKnowledge: true, requiresRuntime: activities.some(a => a.type === 'runtime_practice'), requiresReflection: true }, activities, sources: usableSources.map(source => ({ title: source.title, url: source.url })), sourceStatus: quality >= .65 ? 'grounded' : 'degraded' }; const privateJson = { answerKey: { 'knowledge-1': '正确做法' }, rubric: { 'knowledge-2': '提及条件与结果', scenario: '包含判断与理由', reflection: '包含不确定性和验证动作' }, referenceImplementation: null }; const version = Number((this.repository.db.prepare('SELECT COALESCE(MAX(version),0)+1 AS n FROM practice_cards WHERE learner_id=? AND plan_unit_id=?').get(learnerId, unitId) as Row).n); const id = randomUUID(); const at = now(); this.repository.db.transaction(() => { this.repository.db.prepare("UPDATE practice_cards SET status='superseded', updated_at=? WHERE learner_id=? AND plan_unit_id=? AND status='ready'").run(at, learnerId, unitId); this.repository.db.prepare("INSERT INTO practice_cards(id, learner_id, plan_unit_id, intent_json, public_json, private_json, source_quality, status, version, client_request_id, created_at, ready_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'ready', ?, ?, ?, ?, ?)").run(id, learnerId, unitId, JSON.stringify(derivedIntent), JSON.stringify(publicJson), JSON.stringify(privateJson), quality, version, input.clientRequestId, at, at, at); for (let index=0; index<usableSources.length; index++) this.repository.db.prepare('INSERT INTO practice_card_sources(practice_card_id, source_item_id, relevance, position, created_at) VALUES (?, ?, ?, ?, ?)').run(id, usableSources[index].id, quality, index + 1, at); this.event(id, learnerId, 'ready', { sourceCount: usableSources.length, sourceQuality: quality }, input.clientRequestId) })(); return cardPublic(this.repository.db.prepare('SELECT * FROM practice_cards WHERE id=?').get(id) as Row) }
  card(learnerId: string, id: string) { const row = this.repository.db.prepare('SELECT * FROM practice_cards WHERE id=? AND learner_id=?').get(id, learnerId) as Row | undefined; if (!row) throw new Error('Practice Card 不存在'); return cardPublic(row) }
  cardEvents(learnerId: string, id: string) { this.card(learnerId, id); return this.repository.db.prepare('SELECT sequence, type, payload_json AS payloadJson, created_at AS createdAt FROM practice_card_events WHERE practice_card_id=? ORDER BY sequence').all(id) }
  retryCard(learnerId: string, id: string, key: string) { const old = this.repository.db.prepare('SELECT * FROM practice_cards WHERE id=? AND learner_id=?').get(id, learnerId) as Row | undefined; if (!old) throw new Error('Practice Card 不存在'); return this.createCard(learnerId, String(old.plan_unit_id), { intent: parse(old.intent_json, {}), sourceIds: (this.repository.db.prepare('SELECT source_item_id FROM practice_card_sources WHERE practice_card_id=?').all(id) as Array<{ source_item_id: string }>).map(item => item.source_item_id), clientRequestId: key }) }
  startSession(learnerId: string, cardId: string, clientRequestId: string) { const card = this.repository.db.prepare("SELECT * FROM practice_cards WHERE id=? AND learner_id=? AND status='ready'").get(cardId, learnerId) as Row | undefined; if (!card) throw new Error('可用 Practice Card 不存在'); const existing = this.repository.db.prepare('SELECT * FROM gym_sessions WHERE learner_id=? AND practice_card_id=? AND client_request_id=?').get(learnerId, cardId, clientRequestId) as Row | undefined; if (existing) return this.session(learnerId, String(existing.id)); const unit = this.unit(learnerId, String(card.plan_unit_id)); let buildId: string | null = null; let caseId: string | null = null; const activities = parse<{ activities?: Array<{type?: string}> }>(card.public_json, {}).activities ?? []; if (activities.some(a => a.type === 'runtime_practice')) { const build = this.build.create(learnerId, String(unit.plan_id), String(unit.id), `card:${cardId}:${clientRequestId}`); buildId = build.job.id; caseId = build.job.learningCaseId } const id = randomUUID(); const at = now(); this.repository.db.prepare("INSERT INTO gym_sessions(id, learner_id, practice_card_id, learning_case_id, gym_build_job_id, status, client_request_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 'active', ?, ?, ?)").run(id, learnerId, cardId, caseId, buildId, clientRequestId, at, at); this.sessionEvent(id, 'started', { cardId }, clientRequestId); return this.session(learnerId, id) }
  private sessionEvent(sessionId: string, type: string, payload: Record<string, unknown>, key?: string) { const sequence = Number((this.repository.db.prepare('SELECT COALESCE(MAX(sequence),0)+1 AS n FROM gym_session_events WHERE gym_session_id=?').get(sessionId) as Row).n); this.repository.db.prepare('INSERT INTO gym_session_events(id, gym_session_id, sequence, type, payload_json, client_request_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)').run(randomUUID(), sessionId, sequence, type, JSON.stringify(payload), key ?? null, now()) }
  session(learnerId: string, id: string) { const row = this.repository.db.prepare('SELECT s.*, c.public_json FROM gym_sessions s JOIN practice_cards c ON c.id=s.practice_card_id WHERE s.id=? AND s.learner_id=?').get(id, learnerId) as Row | undefined; if (!row) throw new Error('Gym Session 不存在'); return { id: String(row.id), practiceCardId: String(row.practice_card_id), learningCaseId: row.learning_case_id ? String(row.learning_case_id) : null, gymBuildJobId: row.gym_build_job_id ? String(row.gym_build_job_id) : null, status: String(row.status), stage: String(row.stage), outcome: row.outcome ? String(row.outcome) : null, activities: parse<Record<string, unknown>>(row.public_json, {}).activities ?? [], attempts: this.repository.db.prepare('SELECT activity_key AS activityKey, attempt_no AS attemptNo, result_json AS resultJson, status FROM gym_activity_attempts WHERE gym_session_id=? ORDER BY created_at').all(id), events: this.repository.db.prepare('SELECT sequence, type, payload_json AS payloadJson, created_at AS createdAt FROM gym_session_events WHERE gym_session_id=? ORDER BY sequence').all(id) } }
  answer(learnerId: string, sessionId: string, activityKey: string, answer: unknown, clientRequestId: string) { const row = this.repository.db.prepare('SELECT s.*, c.private_json, c.public_json FROM gym_sessions s JOIN practice_cards c ON c.id=s.practice_card_id WHERE s.id=? AND s.learner_id=? AND s.status=\'active\'').get(sessionId, learnerId) as Row | undefined; if (!row) throw new Error('活动会话不可用'); const attempts = Number((this.repository.db.prepare('SELECT COUNT(*) AS n FROM gym_activity_attempts WHERE gym_session_id=? AND activity_key=?').get(sessionId, activityKey) as Row).n); if (attempts >= 2) throw new Error('每题最多两次作答'); const activity = (parse<{activities?: Array<{key:string; type:string}>}>(row.public_json, {}).activities ?? []).find(item => item.key === activityKey); if (!activity) throw new Error('活动不存在'); const privateData = parse<{answerKey?: Record<string, unknown>; rubric?: Record<string, string>}>(row.private_json, {}); const correct = activity.type === 'knowledge_check' ? String(answer).trim() === String(privateData.answerKey?.[activityKey] ?? '') : Boolean(answer); const result = { correct, feedback: attempts === 0 && !correct ? '再想一想相关概念和边界条件。' : correct ? '回答已记录。' : '可参考解析：先明确条件、证据与结论。', solution: attempts === 0 || correct ? undefined : privateData.rubric?.[activityKey] }; const at = now(); this.repository.db.prepare("INSERT INTO gym_activity_attempts(id, gym_session_id, activity_key, attempt_no, answer_json, result_json, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(randomUUID(), sessionId, activityKey, attempts + 1, JSON.stringify(answer), JSON.stringify(result), correct ? 'passed' : 'needs_review', at, at); this.sessionEvent(sessionId, 'answered', { activityKey, attemptNo: attempts + 1, correct }, clientRequestId); return result }
  draft(learnerId: string, sessionId: string, activityKey: string, answer: unknown, clientRequestId: string) { this.session(learnerId, sessionId); this.sessionEvent(sessionId, 'answer_drafted', { activityKey, answer }, clientRequestId); return { activityKey, saved: true } }
  async startRuntime(learnerId: string, sessionId: string) { const session=this.session(learnerId, sessionId); if (!session.gymBuildJobId) throw new Error('当前卡片没有 runtime 活动'); const result=await this.build.start(learnerId, session.gymBuildJobId); this.sessionEvent(sessionId, 'runtime_started', { gymBuildJobId: session.gymBuildJobId }); return result }
  complete(learnerId: string, sessionId: string, clientRequestId: string) { const session = this.session(learnerId, sessionId); const answers = this.repository.db.prepare("SELECT activity_key, result_json FROM gym_activity_attempts WHERE gym_session_id=? ORDER BY attempt_no DESC").all(sessionId) as Row[]; const knowledgeAnswers = new Map<string, boolean>(); for (const answer of answers.filter(a => String(a.activity_key).startsWith('knowledge'))) if (!knowledgeAnswers.has(String(answer.activity_key))) knowledgeAnswers.set(String(answer.activity_key), Boolean(parse<{correct?:boolean}>(answer.result_json, {}).correct)); const expectedKnowledge=(session.activities as Array<{key?:string;type?:string}>).filter(a=>a.type==='knowledge_check').map(a=>a.key); const knowledge = expectedKnowledge.length >= 2 && expectedKnowledge.every(key => knowledgeAnswers.get(key!) === true); const reflected = answers.some(a => String(a.activity_key) === 'reflection' && Boolean(parse<{correct?:boolean}>(a.result_json, {}).correct)); const runtimeNeeded = (session.activities as Array<{type?:string}>).some(a => a.type === 'runtime_practice'); const runtimeOk = !runtimeNeeded || Boolean(session.gymBuildJobId && this.build.get(learnerId, session.gymBuildJobId).job.status === 'ready'); const status = knowledge && reflected && runtimeOk ? 'completed' : 'completed_with_gaps'; const at = now(); this.repository.db.transaction(() => { this.repository.db.prepare('UPDATE gym_sessions SET status=?, completed_at=?, updated_at=? WHERE id=? AND learner_id=?').run(status, at, at, sessionId, learnerId); this.repository.db.prepare('UPDATE plan_units SET status=CASE WHEN ?=\'completed\' THEN \'completed\' ELSE status END, completed_at=CASE WHEN ?=\'completed\' THEN ? ELSE completed_at END WHERE id=(SELECT plan_unit_id FROM practice_cards WHERE id=(SELECT practice_card_id FROM gym_sessions WHERE id=?))').run(status,status,at,sessionId); this.repository.db.prepare('INSERT INTO gym_profile_evidence(id, learner_id, gym_session_id, evidence_key, content, created_at) VALUES (?, ?, ?, ?, ?, ?)').run(randomUUID(), learnerId, sessionId, 'gym_knowledge', `knowledge=${knowledge}`, at); if (runtimeNeeded) this.repository.db.prepare('INSERT INTO gym_profile_evidence(id, learner_id, gym_session_id, evidence_key, content, created_at) VALUES (?, ?, ?, ?, ?, ?)').run(randomUUID(), learnerId, sessionId, 'gym_runtime', `runtime=${runtimeOk}`, at); if (reflected) this.repository.db.prepare('INSERT INTO gym_profile_evidence(id, learner_id, gym_session_id, evidence_key, content, created_at) VALUES (?, ?, ?, ?, ?, ?)').run(randomUUID(), learnerId, sessionId, 'gym_reflection', 'reflection submitted', at); this.sessionEvent(sessionId, 'completed', { status }, clientRequestId) })(); return this.session(learnerId, sessionId) }
}
