import { randomUUID } from 'node:crypto'
import type { ProductRepository } from './product-repository.js'
import type { EnvironmentBuildOrchestrator } from './gym-build-service.js'
import { LabError } from './errors.js'
type Row=Record<string,unknown>; const now=()=>new Date().toISOString(); const j=<T>(v:unknown,f:T):T=>{try{return typeof v==='string'?JSON.parse(v)as T:f}catch{return f}}
export class MixedGymService {
  constructor(private readonly repository:ProductRepository,private readonly builds:EnvironmentBuildOrchestrator){}
  private unit(l:string,id:string){const r=this.repository.db.prepare('SELECT u.*,p.id plan_id FROM plan_units u JOIN learning_plans p ON p.id=u.plan_id WHERE u.id=? AND p.learner_id=?').get(id,l)as Row|undefined;if(!r)throw new LabError('plan_unit_not_found','学习单元不存在',404);return r}
  private card(l:string,id:string){const r=this.repository.db.prepare('SELECT * FROM practice_cards WHERE id=? AND learner_id=?').get(id,l)as Row|undefined;if(!r)throw new LabError('practice_card_not_found','Practice Card 不存在',404);return r}
  private pub(r:Row){const x=j<Record<string,unknown>>(r.public_json,{});return {id:String(r.id),planUnitId:String(r.plan_unit_id),status:r.status,version:r.version,objective:x.objective,summary:x.summary,mode:x.mode,completionPolicy:x.completionPolicy,sources:x.sources,activities:x.activities,sourceStatus:x.sourceStatus,sourceQuality:r.source_quality}}
  private event(id:string,type:string,payload:Record<string,unknown>,key:string){const n=Number((this.repository.db.prepare('SELECT COALESCE(MAX(sequence),0)+1 n FROM gym_session_events WHERE gym_session_id=?').get(id)as Row).n);this.repository.db.prepare('INSERT OR IGNORE INTO gym_session_events(id,gym_session_id,sequence,type,payload_json,client_request_id,created_at) VALUES(?,?,?,?,?,?,?)').run(randomUUID(),id,n,type,JSON.stringify(payload),key,now())}
  createCard(l:string,unitId:string,key:string){const old=this.repository.db.prepare('SELECT * FROM practice_cards WHERE learner_id=? AND plan_unit_id=? AND client_request_id=?').get(l,unitId,key)as Row|undefined;if(old)return this.pub(old);const u=this.unit(l,unitId), candidates=this.repository.db.prepare('SELECT * FROM learner_source_items WHERE learner_id=? ORDER BY updated_at DESC LIMIT 20').all(l)as Row[], sources=candidates.filter(s=>`${s.title} ${s.excerpt}`.toLowerCase().includes(String(u.title).toLowerCase().slice(0,16))).slice(0,2),q=sources.length?sources.reduce((n,s)=>n+(String(s.excerpt).length>120?.7:.45),0)/sources.length:0,runtime=['lab','workspace'].includes(String(u.learning_mode)),acts=[{key:'concept',type:'concept',prompt:`解释 ${u.title} 的核心概念。`},{key:'knowledge-1',type:'knowledge_check',prompt:'选择正确做法。',choices:['正确做法','常见误解']},{key:'knowledge-2',type:'knowledge_check',prompt:'说明边界条件。'},{key:'scenario',type:'scenario_reasoning',prompt:'说明判断和理由。'},...(runtime?[{key:'runtime',type:'runtime_practice',prompt:'在受控环境验证。'}]:[]),{key:'reflection',type:'reflection',prompt:'记录不确定点和验证动作。'}],pub={title:u.title,objective:u.objective,summary:q>=.65?u.objective:`${u.objective}（无来源降级）`,mode:runtime?'mixed':'knowledge_only',completionPolicy:{requiresKnowledge:true,requiresRuntime:runtime,requiresReflection:true},activities:acts,sources:sources.map(s=>({title:s.title,url:s.url})),sourceStatus:q>=.65?'grounded':'degraded'},priv={answerKey:{'knowledge-1':'正确做法'},rubric:{'knowledge-2':'条件与结论',scenario:'判断和理由',reflection:'不确定性与验证'},referenceImplementation:null},version=Number((this.repository.db.prepare('SELECT COALESCE(MAX(version),0)+1 n FROM practice_cards WHERE learner_id=? AND plan_unit_id=?').get(l,unitId)as Row).n),id=randomUUID(),at=now();this.repository.db.transaction(()=>{this.repository.db.prepare("UPDATE practice_cards SET status='superseded',updated_at=? WHERE learner_id=? AND plan_unit_id=? AND status='ready'").run(at,l,unitId);this.repository.db.prepare("INSERT INTO practice_cards(id,learner_id,plan_unit_id,intent_json,public_json,private_json,source_quality,status,version,client_request_id,created_at,ready_at,updated_at) VALUES(?,?,?,?,?,?,?,'ready',?,?,?,?,?)").run(id,l,unitId,JSON.stringify({targetCapability:u.title,objective:u.objective}),JSON.stringify(pub),JSON.stringify(priv),q,version,key,at,at,at);for(let i=0;i<sources.length;i++)this.repository.db.prepare('INSERT INTO practice_card_sources(practice_card_id,source_item_id,relevance,position,created_at) VALUES(?,?,?,?,?)').run(id,sources[i].id,q,i+1,at)})();return this.pub(this.card(l,id))}
  retryCard(l:string,id:string,key:string){return this.createCard(l,String(this.card(l,id).plan_unit_id),key)}
  cardEvents(l:string,id:string){this.card(l,id);return this.repository.db.prepare('SELECT sequence,type,payload_json payloadJson,created_at createdAt FROM practice_card_events WHERE practice_card_id=? ORDER BY sequence').all(id)}
  private sessionRow(l:string,id:string){const r=this.repository.db.prepare('SELECT s.*,c.public_json,c.private_json,c.plan_unit_id FROM gym_sessions s JOIN practice_cards c ON c.id=s.practice_card_id WHERE s.id=? AND s.learner_id=?').get(id,l)as Row|undefined;if(!r)throw new LabError('gym_session_not_found','Gym Session 不存在',404);return r}
  startSession(l:string,cardId:string,key:string){const c=this.card(l,cardId);if(c.status!=='ready')throw new LabError('practice_card_unavailable','Practice Card 不可用',409);const old=this.repository.db.prepare('SELECT id FROM gym_sessions WHERE learner_id=? AND practice_card_id=? AND client_request_id=?').get(l,cardId,key)as Row|undefined;if(old)return this.session(l,String(old.id));const id=randomUUID(),at=now();this.repository.db.prepare("INSERT INTO gym_sessions(id,learner_id,practice_card_id,status,stage,client_request_id,created_at,updated_at) VALUES(?,?,?,'active','orienting',?,?,?)").run(id,l,cardId,key,at,at);this.event(id,'started',{cardId},key);return this.session(l,id)}
  session(l:string,id:string){const r=this.sessionRow(l,id);return {id:String(r.id),practiceCardId:r.practice_card_id,status:r.status,stage:r.stage,outcome:r.outcome??null,gymBuildJobId:r.gym_build_job_id??null,activities:j<Record<string,unknown>>(r.public_json,{}).activities??[],attempts:this.repository.db.prepare('SELECT activity_key activityKey,attempt_no attemptNo,result_json resultJson,status FROM gym_activity_attempts WHERE gym_session_id=? ORDER BY created_at').all(id),events:this.repository.db.prepare('SELECT sequence,type,payload_json payloadJson,created_at createdAt FROM gym_session_events WHERE gym_session_id=? ORDER BY sequence').all(id)}}
  draft(l:string,id:string,activityKey:string,answer:unknown,key:string){const r=this.sessionRow(l,id),state=j<Record<string,unknown>>(r.activity_state_json,{});state[activityKey]=answer;this.repository.db.prepare('UPDATE gym_sessions SET activity_state_json=?,updated_at=? WHERE id=?').run(JSON.stringify(state),now(),id);this.event(id,'answer_drafted',{activityKey},key);return {activityKey,saved:true}}
  submitActivity(l:string,id:string,k:string,a:unknown,key:string){const r=this.sessionRow(l,id),n=Number((this.repository.db.prepare('SELECT COUNT(*) n FROM gym_activity_attempts WHERE gym_session_id=? AND activity_key=?').get(id,k)as Row).n);if(n>=2)throw new LabError('attempt_limit','每题最多两次提交',409);const act=(j<{activities?:Array<{key:string;type:string}>}>(r.public_json,{}).activities??[]).find(x=>x.key===k);if(!act)throw new LabError('activity_not_found','活动不存在',404);const p=j<{answerKey?:Record<string,unknown>;rubric?:Record<string,string>}>(r.private_json,{}),correct=act.type==='knowledge_check'?String(a).trim()===String(p.answerKey?.[k]??''):Boolean(a),result={correct,feedback:correct?'已记录。':n===0?'请重新检查概念和边界条件。':`可参考解析：${p.rubric?.[k]??'明确条件、证据与结论。'}`},at=now();this.repository.db.prepare('INSERT INTO gym_activity_attempts(id,gym_session_id,activity_key,attempt_no,answer_json,result_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(randomUUID(),id,k,n+1,JSON.stringify(a),JSON.stringify(result),correct?'passed':'needs_review',at,at);this.event(id,'activity_submitted',{activityKey:k,attemptNo:n+1,correct},key);return result}
  async startRuntime(l:string,id:string){const r=this.sessionRow(l,id);if(r.gym_build_job_id)return this.builds.start(l,String(r.gym_build_job_id));const u=this.unit(l,String(r.plan_unit_id)),b=this.builds.create(l,String(u.plan_id),String(u.id),`gym:${id}`);this.repository.db.prepare("UPDATE gym_sessions SET gym_build_job_id=?,learning_case_id=?,stage='preparing_runtime',updated_at=? WHERE id=?").run(b.job.id,b.job.learningCaseId,now(),id);this.event(id,'runtime_started',{gymBuildJobId:b.job.id},`runtime:${id}`);return this.builds.start(l,b.job.id)}
  complete(l:string,id:string,key:string){const r=this.sessionRow(l,id),acts=j<{activities?:Array<{key:string;type:string}>}>(r.public_json,{}).activities??[],rows=this.repository.db.prepare('SELECT activity_key,result_json FROM gym_activity_attempts WHERE gym_session_id=? ORDER BY attempt_no DESC').all(id)as Row[],latest=new Map<string,boolean>();for(const x of rows)if(!latest.has(String(x.activity_key)))latest.set(String(x.activity_key),Boolean(j<{correct?:boolean}>(x.result_json,{}).correct));const know=acts.filter(x=>x.type==='knowledge_check').every(x=>latest.get(x.key)),reflection=Boolean(latest.get('reflection')),runtime=acts.some(x=>x.type==='runtime_practice'),verified=!runtime||Boolean(r.gym_build_job_id&&this.builds.get(l,String(r.gym_build_job_id)).job.status==='ready'&&this.repository.db.prepare("SELECT 1 FROM environment_runtime_bindings WHERE gym_build_job_id=? AND status='ready'").get(r.gym_build_job_id)),outcome=know&&reflection&&verified?'verified':know||reflection||verified?'completed_with_gaps':'incomplete',at=now();this.repository.db.transaction(()=>{this.repository.db.prepare("UPDATE gym_sessions SET status='completed',stage='completed',outcome=?,completed_at=?,updated_at=? WHERE id=?").run(outcome,at,at,id);if(outcome==='verified')this.repository.db.prepare("UPDATE plan_units SET status='completed',completed_at=? WHERE id=?").run(at,r.plan_unit_id);this.event(id,'completed',{outcome},key)})();return this.session(l,id)}
}
