<script setup lang="ts">
import { Play, Terminal, Trash2 } from 'lucide-vue-next'
import type { ProductWorkspaceExecution } from '@/types/product'

defineProps<{ commands: string[]; executions: ProductWorkspaceExecution[]; working?: boolean; disabled?: boolean }>()
const emit = defineEmits<{ execute: [command: string]; reset: []; end: [] }>()
function statusLabel(status: ProductWorkspaceExecution['status']) { return ({ succeeded: '成功', failed: '失败', timed_out: '超时', rejected: '拒绝', running: '运行中', queued: '排队' })[status] ?? status }
</script>

<template>
  <section class="terminal-panel" aria-labelledby="terminal-title"><header class="terminal-heading"><div><span class="eyebrow">Execution evidence</span><h2 id="terminal-title">终端输出</h2></div><div class="terminal-actions"><button v-for="command in commands" :key="command" type="button" :disabled="disabled || working" @click="emit('execute', command)"><Play :size="11" aria-hidden="true" />{{ command }}</button><button type="button" :disabled="disabled || working" title="恢复初始文件" aria-label="恢复初始文件" @click="emit('reset')"><Trash2 :size="12" aria-hidden="true" /></button><button class="end-button" type="button" :disabled="disabled || working" @click="emit('end')">结束工作区</button></div></header><div v-if="!executions.length" class="terminal-empty"><Terminal :size="16" aria-hidden="true" /><span>执行一次 pytest，结果会作为实践证据保存。</span></div><div v-else class="execution-list"><article v-for="execution in [...executions].reverse()" :key="execution.id" class="execution-item"><div class="execution-meta"><code>{{ execution.command }}</code><span :class="execution.status">{{ statusLabel(execution.status) }}</span></div><pre v-if="execution.stdout || execution.stderr">{{ execution.stdout }}{{ execution.stderr ? `\n${execution.stderr}` : '' }}</pre><small v-else>没有输出 · exit {{ execution.exitCode ?? '—' }}</small></article></div></section>
</template>

<style scoped>
.terminal-panel { border: 1px solid var(--line); background: var(--paper-deep); }.terminal-heading { display: flex; align-items: start; justify-content: space-between; gap: 12px; padding: 14px 15px 11px; border-bottom: 1px solid var(--line); }.terminal-heading h2 { margin: 6px 0 0; color: var(--ink); font: 400 21px var(--serif); }.terminal-actions { display: flex; flex-wrap: wrap; justify-content: end; gap: 5px; }.terminal-actions button { display: inline-flex; align-items: center; gap: 5px; min-height: 27px; padding: 5px 7px; border: 1px solid var(--line); background: var(--paper); color: var(--blue); font: 9px var(--mono); }.terminal-actions button:disabled { cursor: wait; opacity: .55; }.terminal-actions .end-button { color: var(--red); }.terminal-empty { display: flex; align-items: center; gap: 8px; min-height: 120px; padding: 15px; color: var(--muted); font-size: 11px; }.execution-list { display: grid; gap: 8px; max-height: 420px; overflow: auto; padding: 12px; }.execution-item { padding: 10px; border-left: 2px solid var(--line); background: var(--paper); }.execution-meta { display: flex; align-items: center; justify-content: space-between; gap: 10px; }.execution-meta code { overflow: hidden; color: var(--ink); text-overflow: ellipsis; white-space: nowrap; }.execution-meta span { padding: 3px 5px; color: var(--muted); font: 9px var(--mono); white-space: nowrap; }.execution-meta span.succeeded { background: var(--green-soft); color: var(--green); }.execution-meta span.failed, .execution-meta span.timed_out, .execution-meta span.rejected { background: var(--red-soft); color: var(--red); }.execution-item pre { max-height: 240px; margin: 8px 0 0; overflow: auto; padding: 9px; background: #222b32; color: #e4ebe5; font: 10px/1.6 var(--mono); white-space: pre-wrap; word-break: break-word; }.execution-item small { display: block; margin-top: 7px; color: var(--muted); font: 9px var(--mono); }
@media (max-width: 680px) { .terminal-heading { align-items: stretch; flex-direction: column; }.terminal-actions { justify-content: start; } }
</style>
