<script setup lang="ts">
import { Save } from 'lucide-vue-next'
import type { ProductWorkspaceFile } from '@/types/product'

defineProps<{ files: ProductWorkspaceFile[]; selectedPath: string | null; content: string; saveState: 'idle' | 'saving' | 'saved' | 'conflict' | 'error'; disabled?: boolean }>()
const emit = defineEmits<{ select: [path: string]; 'update:content': [content: string]; save: [] }>()
</script>

<template>
  <section class="editor-panel" aria-labelledby="editor-title"><header class="panel-heading"><div><span class="eyebrow">Workspace files</span><h2 id="editor-title">代码与材料</h2></div><span class="save-indicator" :class="saveState"><Save :size="12" aria-hidden="true" />{{ saveState === 'saving' ? '保存中…' : saveState === 'saved' ? '已保存' : saveState === 'conflict' ? '版本冲突' : saveState === 'error' ? '保存失败' : '未修改' }}</span></header><div class="editor-body"><nav class="file-list" aria-label="工作区文件"><button v-for="file in files" :key="file.path" type="button" :class="{ active: file.path === selectedPath }" @click="emit('select', file.path)"><span>{{ file.path }}</span><small>r{{ file.revision }}</small></button></nav><div class="editor-main"><div v-if="selectedPath" class="editor-toolbar"><code>{{ selectedPath }}</code><button type="button" :disabled="disabled" @click="emit('save')"><Save :size="12" aria-hidden="true" />立即保存</button></div><textarea v-if="selectedPath" :value="content" :disabled="disabled" spellcheck="false" aria-label="当前文件内容" @input="emit('update:content', ($event.target as HTMLTextAreaElement).value)" /><div v-else class="editor-empty">选择一个文件开始阅读。</div></div></div></section>
</template>

<style scoped>
.editor-panel { min-width: 0; border: 1px solid var(--line); background: var(--paper-deep); }.panel-heading { display: flex; align-items: start; justify-content: space-between; gap: 12px; padding: 14px 15px 11px; border-bottom: 1px solid var(--line); }.panel-heading h2 { margin: 6px 0 0; color: var(--ink); font: 400 21px var(--serif); }.save-indicator { display: inline-flex; align-items: center; gap: 5px; padding: 4px 6px; color: var(--muted); font: 9px var(--mono); }.save-indicator.saved { color: var(--green); }.save-indicator.saving { color: var(--blue); }.save-indicator.conflict, .save-indicator.error { color: var(--red); }.editor-body { display: grid; grid-template-columns: 170px minmax(0, 1fr); min-height: 480px; }.file-list { display: grid; align-content: start; gap: 1px; padding: 8px; border-right: 1px solid var(--line); background: var(--paper); }.file-list button { display: flex; align-items: center; justify-content: space-between; gap: 8px; min-width: 0; padding: 8px 7px; border: 0; border-left: 2px solid transparent; background: transparent; color: var(--muted); text-align: left; cursor: pointer; }.file-list button.active { border-left-color: var(--orange); background: var(--orange-soft); color: var(--ink); }.file-list button span { overflow: hidden; font: 9px var(--mono); text-overflow: ellipsis; white-space: nowrap; }.file-list button small { color: var(--muted); font: 8px var(--mono); }.editor-main { display: grid; grid-template-rows: auto minmax(0, 1fr); min-width: 0; }.editor-toolbar { display: flex; align-items: center; justify-content: space-between; gap: 8px; padding: 8px 10px; border-bottom: 1px solid var(--line-soft); }.editor-toolbar code { overflow: hidden; color: var(--blue); text-overflow: ellipsis; white-space: nowrap; }.editor-toolbar button { display: inline-flex; align-items: center; gap: 5px; padding: 5px 7px; border: 1px solid var(--line); background: var(--paper); color: var(--blue); font: 9px var(--mono); white-space: nowrap; }.editor-toolbar button:disabled { cursor: wait; opacity: .55; }.editor-main textarea { width: 100%; min-height: 420px; padding: 15px; border: 0; outline: 0; resize: none; background: #222b32; color: #e4ebe5; font: 12px/1.7 var(--mono); tab-size: 4; }.editor-empty { display: grid; place-items: center; color: var(--muted); font-size: 11px; }
@media (max-width: 640px) { .editor-body { grid-template-columns: 1fr; min-height: 0; }.file-list { grid-template-columns: repeat(2, minmax(0, 1fr)); border-right: 0; border-bottom: 1px solid var(--line); }.editor-main textarea { min-height: 380px; } }
</style>
