<script setup lang="ts">
import { CheckCircle2, FileText } from 'lucide-vue-next'
import ResumeUploadField from '@/components/onboarding/ResumeUploadField.vue'
import type { AgentPlanningSession } from '@/types/product'

defineProps<{ session: AgentPlanningSession; uploading?: boolean; uploadError?: string | null; resumeNotice?: string | null }>()
const emit = defineEmits<{ upload: [payload: { file: File | null; valid: boolean }] }>()
const sourceLabels: Record<string, string> = { user_message: '对话', resume: '简历', diagnostic_assessment: '诊断评估', 'lab/workspace_verification': '实践验证', 'lab/workspace verification': '实践验证', lab_verification: '实践验证', workspace_verification: '实践验证' }
</script>

<template>
  <aside class="profile-panel" aria-labelledby="profile-panel-title"><div class="panel-heading"><CheckCircle2 :size="15" aria-hidden="true" /><span id="profile-panel-title">画像正在形成</span></div><div class="goal"><small>当前目标</small><strong>{{ session.goal }}</strong></div><div class="stage-progress"><small>当前阶段</small><strong>{{ session.stage }}</strong><span>{{ session.progress.completed }} / {{ session.progress.total }} 已完成</span></div><div v-if="session.profile?.dimensions.length" class="dimensions"><small>能力线索</small><div v-for="dimension in session.profile.dimensions" :key="dimension.key" class="dimension"><strong>{{ dimension.key }}</strong><span>{{ dimension.summary }}</span></div></div><div v-if="session.profile?.evidence.length" class="evidence-badges"><small>证据来源</small><div class="badge-list"><span v-for="source in session.profile.evidence" :key="source.id" class="source-badge">{{ sourceLabels[source.sourceType] ?? source.sourceType }}</span></div></div><div v-if="session.resume" class="resume-attached"><FileText :size="14" aria-hidden="true" /><span>{{ session.resume.originalFilename }}</span><small>第 {{ session.resume.version }} 版 · {{ session.resume.pageCount }} 页 · {{ session.resume.textLength }} 字 · 已纳入规划上下文</small></div><ResumeUploadField :disabled="uploading" :current-name="session.resume?.originalFilename" @change="emit('upload', $event)" /><p v-if="uploading" class="upload-state">正在解析并更新规划上下文…</p><p v-if="resumeNotice" class="resume-notice" role="status">{{ resumeNotice }}</p><p v-if="uploadError" class="upload-error" role="alert">{{ uploadError }}</p><p class="panel-note">路线生成由服务端门禁控制：测评结束并确认需求摘要后才会开放。</p></aside>
</template>

<style scoped>
.profile-panel { align-self: start; padding: 15px 0; border-top: 2px solid var(--orange); border-bottom: 1px solid var(--line); }.panel-heading { display: flex; align-items: center; gap: 8px; color: var(--blue); font: 9px var(--mono); text-transform: uppercase; }.goal { margin-top: 20px; }.goal small, .dimensions > small, .stage-progress small, .evidence-badges > small { color: var(--muted); font: 9px var(--mono); }.goal strong { display: block; margin-top: 7px; color: var(--ink); font: 400 18px/1.35 var(--serif); }.stage-progress { display: grid; gap: 4px; margin-top: 18px; padding: 10px; background: var(--paper-muted); }.stage-progress strong { color: var(--ink); font-size: 11px; font-weight: 500; }.stage-progress span { color: var(--muted); font: 9px var(--mono); }.topic-list { display: grid; gap: 11px; margin-top: 22px; }.topic { display: flex; align-items: start; gap: 8px; }.topic-mark { display: inline-flex; padding-top: 1px; color: var(--muted); }.topic-mark.covered { color: var(--green); }.topic strong { display: block; color: #4d5a53; font-size: 11px; font-weight: 500; }.topic small { display: block; margin-top: 3px; color: var(--muted); font: 8px var(--mono); }.dimensions { display: grid; gap: 8px; margin-top: 22px; padding-top: 13px; border-top: 1px solid var(--line); }.dimension { display: grid; gap: 3px; }.dimension strong { color: #4d5a53; font-size: 10px; }.dimension span { color: var(--muted); font-size: 10px; line-height: 1.5; }.evidence-badges { display: grid; gap: 8px; margin-top: 20px; padding-top: 13px; border-top: 1px solid var(--line); }.badge-list { display: flex; flex-wrap: wrap; gap: 5px; }.source-badge { padding: 4px 6px; background: var(--blue-soft); color: var(--blue); font: 8px var(--mono); }.resume-attached { display: grid; grid-template-columns: auto minmax(0, 1fr); gap: 5px 7px; margin-top: 20px; padding-top: 13px; border-top: 1px solid var(--line); color: var(--ink); font-size: 10px; }.resume-attached span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.resume-attached small { grid-column: 2; color: var(--muted); font: 8px var(--mono); }.upload-state, .resume-notice, .upload-error { margin: 0; font: 9px/1.55 var(--mono); }.upload-state { color: var(--blue); }.resume-notice { color: #936c18; }.upload-error { color: var(--red); }.panel-note { margin: 22px 0 0; padding-top: 12px; border-top: 1px solid var(--line); color: var(--muted); font: 10px/1.6 var(--mono); }
</style>
