import { defineStore } from 'pinia'
import { ref } from 'vue'
import { createAgentPlanningSession, createAgentRoadmap, getAgentPlanningSession, getAgentRoadmapGeneration, retryAgentInvocation, sendAgentPlanningMessage, uploadPlanningResume } from '@/api/planningService'
import type { AgentPlanningSession, AgentRoadmapGeneration, PlanningStreamEvent } from '@/types/product'

export const usePlanningAgentStore = defineStore('planningAgent', () => {
  const session = ref<AgentPlanningSession | null>(null); const streaming = ref(false); const generating = ref(false); const generation = ref<AgentRoadmapGeneration | null>(null); const streamingAssistant = ref(''); const question = ref(''); const canGenerateRoadmap = ref(false); const error = ref<string | null>(null); const failedInvocationId = ref<string | null>(null)
  function apply(event: PlanningStreamEvent) { if (event.type === 'assistant_delta') streamingAssistant.value += event.delta; if (event.type === 'next_question') { question.value = event.question; canGenerateRoadmap.value = event.canGenerateRoadmap }; if (event.type === 'completed') { session.value = event.session; streamingAssistant.value = '' } if (event.type === 'failed') { error.value = event.message; failedInvocationId.value = event.invocationId } }
  async function run(request: (onEvent: (event: PlanningStreamEvent) => void) => Promise<void>) { streaming.value = true; error.value = null; failedInvocationId.value = null; streamingAssistant.value = ''; try { await request(apply) } catch (cause) { error.value = cause instanceof Error ? cause.message : '规划服务不可用'; throw cause } finally { streaming.value = false } }
  async function start(message: string, resume?: File) { await run((onEvent) => createAgentPlanningSession(message, crypto.randomUUID(), onEvent)); if (session.value && resume) session.value.resume = await uploadPlanningResume(session.value.id, resume) as AgentPlanningSession['resume']; return session.value }
  async function load(id: string) { streaming.value = true; error.value = null; try { session.value = await getAgentPlanningSession(id); canGenerateRoadmap.value = true; return session.value } catch (cause) { error.value = cause instanceof Error ? cause.message : '规划会话加载失败'; throw cause } finally { streaming.value = false } }
  async function send(message: string) { if (!session.value) throw new Error('规划会话尚未加载'); const requestId = crypto.randomUUID(); await run((onEvent) => sendAgentPlanningMessage(session.value!.id, message, requestId, onEvent)); return session.value }
  async function retry() { if (!failedInvocationId.value) return; await run((onEvent) => retryAgentInvocation(failedInvocationId.value!, onEvent)) }
  async function generate() { if (!session.value) throw new Error('规划会话尚未加载'); generating.value = true; error.value = null; try { generation.value = await createAgentRoadmap(session.value.id, crypto.randomUUID()); for (let attempt = 0; attempt < 80 && generation.value.status !== 'succeeded' && generation.value.status !== 'failed'; attempt += 1) { await new Promise((resolve) => window.setTimeout(resolve, 350)); generation.value = await getAgentRoadmapGeneration(generation.value.id) } if (generation.value.status === 'failed') throw new Error(generation.value.failureMessage ?? '路线生成失败'); return generation.value } catch (cause) { error.value = cause instanceof Error ? cause.message : '路线生成失败'; throw cause } finally { generating.value = false } }
  return { session, streaming, generating, generation, streamingAssistant, question, canGenerateRoadmap, error, failedInvocationId, start, load, send, retry, generate }
})
