import { defineStore } from 'pinia'
import { ref } from 'vue'
import { createClientId } from '@/utils/client-id'
import { completeRoadmapNode, confirmPlanAdjustment, confirmRoadmap, createPlanAdjustment, getCurrentRoadmap, getKnowledgeRoute, getPlanAdjustment, getRoadmapDraft, getRoadmapNodes, getRoadmapTree, sendKnowledgeFeedback } from '@/api/planningService'
import type { CurrentRoadmapResponse, KnowledgeRoute, ProductPlanAdjustment, RoadmapDraft, RoadmapNode, RoadmapTree } from '@/types/product'

export const useRoadmapStore = defineStore('roadmap', () => {
  const current = ref<CurrentRoadmapResponse | null>(null); const tree = ref<RoadmapTree | null>(null); const draft = ref<RoadmapDraft | null>(null); const adjustment = ref<ProductPlanAdjustment | null>(null); const children = ref<Record<string, RoadmapNode[]>>({}); const nodeById = ref<Record<string, RoadmapNode>>({}); const knowledgeRoutes = ref<Record<string, KnowledgeRoute>>({}); const knowledgeLoading = ref(false); const knowledgeError = ref<string | null>(null); const loading = ref(false); const error = ref<string | null>(null)
  function resetTree() { tree.value = null; children.value = {}; nodeById.value = {} }
  function mergeTree(next: RoadmapTree) { tree.value = next; const grouped = { ...children.value }; const indexed = { ...nodeById.value }; next.nodes.forEach((node) => { indexed[node.id] = node; if (!node.parentId) return; const list = grouped[node.parentId] ?? []; grouped[node.parentId] = [...list.filter((item) => item.id !== node.id), node].sort((a, b) => a.position - b.position) }); children.value = grouped; nodeById.value = indexed }
  async function loadTree(roadmapId: string, focusNodeId: string | null = null) { const next = await getRoadmapTree(roadmapId, focusNodeId); mergeTree(next); return next }
  async function loadCurrent(focusNodeId: string | null = null) { loading.value = true; error.value = null; try { const next = await getCurrentRoadmap(); const roadmapChanged = current.value?.roadmap?.id !== next.roadmap?.id; current.value = next; if (roadmapChanged) resetTree(); if (next.roadmap) await loadTree(next.roadmap.id, focusNodeId ?? next.currentLearning?.roadmapNodeId ?? null); return current.value } catch (cause) { error.value = cause instanceof Error ? cause.message : '路线图加载失败'; throw cause } finally { loading.value = false } }
  async function loadDraft(id: string) { loading.value = true; error.value = null; try { draft.value = await getRoadmapDraft(id); return draft.value } catch (cause) { error.value = cause instanceof Error ? cause.message : '路线草案加载失败'; throw cause } finally { loading.value = false } }
  async function loadChildren(roadmapId: string, parentId: string | null) { const key = parentId ?? 'root'; if (children.value[key]) return children.value[key]; try { const page = await getRoadmapNodes(roadmapId, parentId); children.value[key] = page.nodes; return page.nodes } catch (cause) { error.value = cause instanceof Error ? cause.message : '路线分支加载失败'; throw cause } }
  async function confirm(id: string, revision: number, startUnitKey?: string) { loading.value = true; try { const result = await confirmRoadmap(id, revision, startUnitKey); await loadCurrent(); return result } finally { loading.value = false } }
  async function requestAdjustment(planId: string, requestText: string) { loading.value = true; error.value = null; try { adjustment.value = await createPlanAdjustment(planId, requestText, createClientId()); return adjustment.value } catch (cause) { error.value = cause instanceof Error ? cause.message : '调整草案生成失败'; throw cause } finally { loading.value = false } }
  async function confirmAdjustment(id: string) { loading.value = true; error.value = null; try { const result = await confirmPlanAdjustment(id); adjustment.value = await getPlanAdjustment(id); await loadCurrent(); return result } catch (cause) { error.value = cause instanceof Error ? cause.message : '调整确认失败'; throw cause } finally { loading.value = false } }
  async function complete(roadmapId: string, node: RoadmapNode, status: 'completed' | 'self_reported' = 'completed') { const updated = await completeRoadmapNode(roadmapId, node.id, node.progressRevision, status); const list = children.value[node.parentId ?? 'root']; if (list) { const found = list.findIndex((item) => item.id === node.id); if (found >= 0) list[found] = updated } return updated }
  async function loadKnowledge(roadmapId: string, nodeId: string, refresh = false) { knowledgeLoading.value = true; knowledgeError.value = null; try { const route = await getKnowledgeRoute(roadmapId, nodeId, refresh); knowledgeRoutes.value[nodeId] = route; return route } catch (cause) { knowledgeError.value = cause instanceof Error ? cause.message : '知乎学习路径加载失败'; throw cause } finally { knowledgeLoading.value = false } }
  async function feedback(routeSetId: string, sourceItemId: string, value: 'read' | 'too_hard' | 'too_easy' | 'irrelevant' | 'helpful') { await sendKnowledgeFeedback(routeSetId, sourceItemId, value) }
  return { current, tree, draft, adjustment, children, nodeById, knowledgeRoutes, knowledgeLoading, knowledgeError, loading, error, loadCurrent, loadTree, loadDraft, loadChildren, confirm, requestAdjustment, confirmAdjustment, complete, loadKnowledge, feedback }
})
