<script setup lang="ts">
import { ExternalLink, LoaderCircle, RefreshCw, Sparkles } from 'lucide-vue-next'
import type { KnowledgeRoute } from '@/types/product'

defineProps<{ route: KnowledgeRoute | undefined; loading: boolean; error: string | null }>()
const emit = defineEmits<{ load: []; refresh: []; feedback: [sourceItemId: string, value: 'read' | 'too_hard' | 'too_easy' | 'irrelevant' | 'helpful'] }>()
const labels: Record<string, string> = { foundation: '基础', case: '案例', extension: '延伸' }
</script>

<template>
  <section class="knowledge-route" aria-labelledby="knowledge-route-title"><div class="route-heading"><div><span class="route-kicker"><Sparkles :size="13" aria-hidden="true" />知乎学习路径</span><h3 id="knowledge-route-title">为这个节点挑三篇</h3></div><button v-if="route" class="icon-button" type="button" title="换一组材料" aria-label="换一组材料" @click="emit('refresh')"><RefreshCw :size="14" aria-hidden="true" /></button></div><button v-if="!route && !loading" class="route-load" type="button" @click="emit('load')"><Sparkles :size="14" aria-hidden="true" />查看相关材料</button><div v-if="loading" class="route-loading"><LoaderCircle :size="15" class="spin" aria-hidden="true" />正在整理相关材料…</div><p v-if="error" class="route-error" role="alert">{{ error }}</p><div v-if="route" class="route-items"><article v-for="item in route.items" :key="item.id" class="route-item"><div class="item-meta"><span>{{ labels[item.role] ?? item.role }}</span><small>{{ item.source.author || '知乎作者未标注' }}</small></div><a :href="item.source.url" target="_blank" rel="noreferrer">{{ item.source.title }} <ExternalLink :size="12" aria-hidden="true" /></a><p>{{ item.source.excerpt }}</p><small class="question">带着这个问题读：{{ item.learningQuestion }}</small><div class="feedback"><button type="button" @click="emit('feedback', item.sourceItemId, 'read')">已读</button><button type="button" @click="emit('feedback', item.sourceItemId, 'helpful')">有帮助</button><button type="button" @click="emit('feedback', item.sourceItemId, 'too_hard')">太难</button><button type="button" @click="emit('feedback', item.sourceItemId, 'too_easy')">太简单</button><button type="button" @click="emit('feedback', item.sourceItemId, 'irrelevant')">不相关</button></div></article></div></section>
</template>

<style scoped>
.knowledge-route { display: grid; gap: 11px; margin-top: 17px; padding-top: 15px; border-top: 1px solid var(--line); }.route-heading { display: flex; align-items: start; justify-content: space-between; gap: 8px; }.route-kicker { display: inline-flex; align-items: center; gap: 6px; color: var(--blue); font: 9px var(--mono); }.route-heading h3 { margin: 6px 0 0; color: var(--ink); font: 400 18px var(--serif); }.icon-button { display: inline-flex; align-items: center; justify-content: center; width: 29px; height: 29px; border: 1px solid var(--line); background: var(--paper); color: var(--blue); cursor: pointer; }.route-load { display: inline-flex; align-items: center; justify-content: center; gap: 6px; min-height: 34px; border: 1px solid var(--line); background: var(--paper-muted); color: var(--blue); font-size: 10px; cursor: pointer; }.route-loading { display: flex; align-items: center; gap: 7px; color: var(--muted); font: 10px var(--mono); }.spin { animation: spin 1s linear infinite; }.route-error { margin: 0; padding: 9px; background: var(--red-soft); color: var(--red); font-size: 10px; line-height: 1.5; }.route-items { display: grid; gap: 11px; }.route-item { padding: 11px; border: 1px solid var(--line-soft); background: var(--paper-deep); }.item-meta { display: flex; justify-content: space-between; gap: 8px; color: var(--orange); font: 8px var(--mono); }.item-meta small { color: var(--muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.route-item a { display: flex; align-items: start; gap: 5px; margin-top: 7px; color: var(--ink); font-size: 11px; line-height: 1.45; text-decoration: none; }.route-item a:hover { color: var(--blue); }.route-item p { margin: 6px 0 0; color: var(--muted); font-size: 10px; line-height: 1.55; }.question { display: block; margin-top: 7px; color: #6f7874; font: 9px/1.5 var(--mono); }.feedback { display: flex; flex-wrap: wrap; gap: 5px; margin-top: 9px; }.feedback button { padding: 4px 6px; border: 1px solid var(--line); background: var(--paper); color: var(--muted); font-size: 8px; cursor: pointer; }.feedback button:hover { border-color: var(--blue); color: var(--blue); }
@keyframes spin { to { transform: rotate(360deg); } }
</style>
