<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted } from 'vue'
import { AlertCircle, ArrowLeft } from 'lucide-vue-next'
import { useRoute, useRouter } from 'vue-router'
import WorkspaceEditor from '@/components/case-workspace/WorkspaceEditor.vue'
import WorkspaceTaskRail from '@/components/case-workspace/WorkspaceTaskRail.vue'
import WorkspaceTerminal from '@/components/case-workspace/WorkspaceTerminal.vue'
import TutorAgent from '@/components/learning/TutorAgent.vue'
import AsyncState from '@/components/shared/AsyncState.vue'
import { useCaseWorkspaceStore } from '@/stores/caseWorkspace'

const route = useRoute(); const router = useRouter(); const store = useCaseWorkspaceStore(); const workspace = computed(() => store.workspace); const spec = computed(() => workspace.value?.case.spec ?? null); const disabled = computed(() => !workspace.value || !['active', 'executing'].includes(workspace.value.workspace.status)); const commands = computed(() => spec.value ? [...new Set([...spec.value.verification.commands, ...spec.value.tasks.flatMap((task) => task.recommendedCommands)])] : [])
async function execute(command: string) { await store.saveFile(); await store.execute(command) }
function updateContent(content: string) { store.editorContent = content; store.scheduleSave() }
async function leave() { await store.saveFile(); await router.push({ name: 'roadmap' }) }
onMounted(() => void store.loadWorkspace(String(route.params.workspaceRunId)))
onBeforeUnmount(() => { void store.saveFile(); store.dispose() })
</script>

<template>
  <div class="page code-workspace-page"><AsyncState :loading="store.loading" :error="store.error && !workspace ? store.error : null"><template #default><template v-if="workspace && spec"><header class="workspace-header"><div><button class="back-button" type="button" @click="leave"><ArrowLeft :size="13" aria-hidden="true" />返回路线图</button><span class="eyebrow">Python workspace · {{ workspace.workspace.status }}</span><h1>{{ spec.title }}</h1><p>{{ spec.learningGoal }}</p></div><div class="header-meta"><span>{{ workspace.case.provider }}</span><span>{{ workspace.workspace.templateKey }}</span><span>租约至 {{ workspace.workspace.leaseExpiresAt ? new Date(workspace.workspace.leaseExpiresAt).toLocaleTimeString() : '—' }}</span></div></header><div v-if="workspace.completion?.status === 'verified'" class="completion-banner verified" role="status"><strong>案例已验证，路线节点已点亮。</strong><button type="button" @click="router.push({ name: 'roadmap' })">查看路线图</button><button type="button" @click="router.push({ name: 'writing', query: { runId: workspace.practice.id } })">进入写作沉淀</button></div><div v-else-if="workspace.completion?.status === 'not_matched'" class="completion-banner" role="status"><span>验证命令已执行，但成功信号尚未全部出现。</span><button type="button" :disabled="store.working" @click="store.recheckCompletion">重新检查</button></div><div v-if="store.error" class="workspace-error" role="alert"><AlertCircle :size="14" aria-hidden="true" />{{ store.error }}</div><div class="workspace-grid"><WorkspaceTaskRail :spec="spec" :executions="workspace.executions" :completion="workspace.completion" :disabled="disabled || store.working" @execute="execute" /><main class="workbench"><WorkspaceEditor :files="workspace.files" :selected-path="store.selectedPath" :content="store.editorContent" :save-state="store.saveState" :disabled="disabled" @select="store.selectFile" @update:content="updateContent" @save="store.saveFile" /><WorkspaceTerminal :commands="commands" :executions="workspace.executions" :working="store.working" :disabled="disabled" @execute="execute" @reset="store.reset" @end="store.end" /></main><aside class="workspace-tutor"><TutorAgent :messages="store.tutorMessages" :sources="store.tutorSources" :loading="store.tutorLoading" :current-gap="store.tutorCurrentGap" :current-question="store.tutorNextQuestion" :failure="store.tutorFailure" :pinned-ids="store.tutorPinnedIds" :disabled="disabled || workspace.practice.status === 'resolved'" eyebrow="Workspace Tutor" title="和你的代码导师讨论" empty-title="从当前代码开始" empty-description="告诉我你从代码、测试或终端输出中观察到了什么。我会帮你整理证据和下一步验证。" placeholder="描述你看到的代码行为、测试错误或下一步判断…" @ask="store.askTutor" @retry="store.retryTutor" @pin="store.pinTutor" /></aside></div></template><section v-else class="missing-workspace"><h2>工作区不可用</h2><p>这个工作区可能已结束或租约已到期，请从路线节点重新开始。</p><button class="secondary-button" type="button" @click="router.push({ name: 'roadmap' })">返回路线图</button></section></template></AsyncState></div>
</template>

<style scoped>
.code-workspace-page { max-width: 1420px; }.workspace-header { display: flex; align-items: flex-start; flex-direction: column; justify-content: space-between; gap: 16px; padding-bottom: 16px; border-bottom: 2px solid var(--blue); }.back-button { display: inline-flex; align-items: center; gap: 6px; margin-bottom: 13px; padding: 5px 0; border: 0; background: transparent; color: var(--blue); font: 9px var(--mono); }.workspace-header h1 { margin: 7px 0 0; color: #2e48cc; font: 400 clamp(25px, 3vw, 37px)/1.2 var(--serif); }.workspace-header p { max-width: 720px; margin: 8px 0 0; color: var(--muted); font-size: 11px; line-height: 1.6; }.header-meta { display: flex; flex-wrap: wrap; justify-content: start; gap: 7px; }.header-meta span { padding: 5px 7px; border: 1px solid var(--line); background: var(--paper-deep); color: var(--muted); font: 9px var(--mono); }.completion-banner { display: flex; align-items: center; flex-wrap: wrap; gap: 9px; margin-top: 12px; padding: 10px 12px; border-left: 2px solid var(--orange); background: var(--orange-soft); color: var(--ink); font-size: 11px; }.completion-banner.verified { border-left-color: var(--green); background: var(--green-soft); }.completion-banner button { border: 1px solid var(--line); background: var(--paper); color: var(--blue); font: 9px var(--mono); padding: 5px 7px; }.workspace-grid { display: grid; grid-template-columns: 260px minmax(0, 1fr) 340px; gap: 16px; margin-top: 16px; align-items: stretch; min-height: calc(100dvh - 240px); }.workbench { display: grid; grid-template-rows: minmax(0, 1fr) minmax(220px, .48fr); gap: 13px; min-width: 0; min-height: 0; }.workspace-tutor { min-width: 0; min-height: 560px; }.workspace-tutor :deep(.tutor-agent) { height: calc(100dvh - 240px); min-height: 560px; }.workspace-error { display: flex; align-items: center; gap: 7px; margin-top: 12px; padding: 9px 11px; border-left: 2px solid var(--red); background: var(--red-soft); color: var(--red); font-size: 10px; }.missing-workspace { padding: 22px 18px; border-top: 2px solid var(--red); background: var(--paper-deep); }.missing-workspace h2 { margin: 0; color: var(--ink); font: 400 22px var(--serif); }.missing-workspace p { color: var(--muted); font-size: 11px; }.missing-workspace button { margin-top: 5px; }
@media (max-width: 1240px) { .workspace-grid { grid-template-columns: 220px minmax(0, 1fr); }.workspace-tutor { grid-column: 1 / -1; min-height: 520px; }.workspace-tutor :deep(.tutor-agent) { height: 520px; min-height: 520px; } }
@media (max-width: 760px) { .workspace-grid { grid-template-columns: 1fr; }.workspace-header h1 { font-size: 28px; } }
</style>
